name: Build Alfresco content model

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Package Alfresco content model
        run: mvn clean package

      - name: Platform jar as artifact
        uses: actions/upload-artifact@v2
        with:
          name: openzaak-alfresco-platform.jar
          path: openzaak-alfresco-platform/target/openzaak-alfresco-platform-*.jar

      - name: Platform jar as artifact
        uses: actions/upload-artifact@v2
        with:
          name: openzaak-alfresco-share.jar
          path: openzaak-alfresco-share/target/openzaak-alfresco-share-*.jar

  #build-docker-image:
  #  runs-on: ubuntu-latest
  #  needs: build-model
  #  steps:
  #    - uses: actions/checkout@v2
      - name: Build docker image
        run: docker-compose -f target/classes/docker/docker-compose.yml build

      - name: Push to docker image repository
        run: echo "TODO"
